config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :tweets
  resources :blogs
  # Defines the root path route ("/")
  # root "posts#index"
 
  root to: 'blogs#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
     has_one_attached :image
     has_many :blog_tag_relations, dependent: :destroy
     has_many :tags, through: :blog_tag_relations, dependent: :destroy
    after_create :renzoku_hantei

    private
    def renzoku_hantei
    puts "始まったよー！！"
    user = self.user
    today = user.remind_date
    toukoubi = created_at.to_date
    last_date = user.last_tweeted_date
    return if last_date == today

    puts "同日投稿判定を潜り抜けたよ！"
        if last_date == today - 1
        new_kaisuu = user.kaisuu.to_i + 1
        puts "回数が増えたよ！"
        else
        puts "1回目だよ！"
        new_kaisuu = 1
        end
        user.update!(
    kaisuu: new_kaisuu,
    last_tweeted_date: today
    )
end
end

app/models/blog_tag_relation.rb
class BlogTagRelation < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :blog_tag_relations, dependent: :destroy
    has_many :blogs, through: :blog_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blogs, dependent: :destroy
         validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :normalize_datetime_params

  private
  def normalize_datetime_params
    # ここに入れるキーは実際に使っているものを追加/削除してOK
    %i[date start_date start_time from to tweeted_date remind_date].each do |k|
      next unless params.key?(k)

      v = params[k]
      # "0" や空は削除（クエリに流さない）
      if v.blank? || v == '0'
        params.delete(k)
        next
      end

      # 文字列なら安全にTimeへ
      if v.is_a?(String)
        begin
          params[k] = Time.zone.parse(v)
        rescue ArgumentError, TypeError
          params.delete(k) # 解析できない値は捨てる
        end
      end
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  after_action :kakuninn, only:[:index]
  before_action :authenticate_user!, only: [:new, :create, :index]
   
  def index
      @tweets = Tweet.all
    if params[:tag]
      Tag.create(name: params[:tag])
    end
  @blogs = Blog.all
  if params[:tag_ids]
      @blogs = []
      params[:tag_ids].each do |key, value|      
        @blogs += Tag.find_by(name: key).blogs if value == "1"
      end
      @blogs.uniq!
    end
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    blog = Blog.new(blog_params)

    blog.user_id = current_user.id  #追記

    if blog.save!
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end
    
    def kakuninn
        user = current_user
        time = Time.now
        jtime = Time.at(time, in: "+09:00")
        user = current_user
        if user.last_tweeted_date.nil?
          user.update!(last_tweeted_date: Date.today)
        end
        user.update!(remind_date: Date.today)
    end

private

  def blog_params
    params.require(:blog).permit(:title, :content, :start_time, :image, tag_ids: [])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end

    def new
    @tweet = Tweet.new
    end

    def create
        tweet = Tweet.new(tweet_params)
        if tweet.save!
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end

  def edit
    @tweet = Tweet.find(params[:id])
  end

   def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:goal)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="title-font"%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  
  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="remind">
 <% if current_user.kaisuu == 1 %>
  <h1>前日の投稿がされていません！
  今日投稿してみませんか？</h1>
 <% else %>
  <p>現在の連続投稿回数 <%= current_user.kaisuu %>回</p>
 <% end %>
</div>

<div class="index">
 <table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td class="blog-title"><%= blog.title %></td>
        <td class="blog-content"><%= blog.content %></td>
        <td><%= link_to '投稿を見る', blog, class: "btn-link" %></td>
        <td><%= link_to '投稿を編集する', edit_blog_path(blog.id), class: "btn-link" %></td>
        <td><%= button_to 'Destroy', blog_path(blog.id), 
        method: :delete, 
        data: { confirm: 'Are you sure?' },
        class: "btn-link" %></td>
        <td> <% if blog.image.attached? %>
            <%= image_tag blog.image, size: '250x200'%>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
 </table>

 <div class="goal">
   <h1>目標</h1>

   <div class="mo">
     <% @tweets.each do |t| %>
      <p><%= t.goal %></p>
      <%= link_to "編集する", edit_tweet_path(t.id), class: "btn-edit" %>
     <% end %>
   </div>
 </div>
</div>

<br>


<%= link_to '日記をかく', new_blog_path, class: "btn-link" %>

<%= month_calendar events: @blogs,attribute: :start_time, start_date_param: :start_date do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>
<%= form_tag({controller:"blogs",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
<% end %>

<div class="form2">
    <%= submit_tag '検索' %>
    <%= form_tag({controller:"blogs",action:"index"}, method: :get) do %>
      <%= text_field_tag :tag %>
     <%= submit_tag 'タグを追加' %>
    <% end %>
</div>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
   <div class="form-group">
        <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
   </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  
  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>
<% @blog.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>
<%= link_to '編集する', edit_blog_path(@blog) %> |
<%= link_to '戻る', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalenDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
 <header>
    <h1>CalenDo</h1>
    <div class=new-goal><%= link_to "新規目標設定", new_tweet_path %></div>
    <div class=my-page> <% if user_signed_in? %>
    <%= link_to "マイページ", user_path(current_user.id) %>
    <% end %></div>
    <div class=back><%= link_to 'カレンダーに戻る', blogs_path %></div>
 </header>
 <main>
  <%= yield %>
 </main>
 <footer>
  <div class="header-list">
    <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </footer>
 </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <div class=edit>目標編集</div>
  <%= f.label :goal %>
  <%= f.text_field :goal, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>目標一覧</h1>
<%= link_to "新規目標設定", new_tweet_path, class: "btn-edit" %>
<%= link_to 'カレンダーに戻る', blogs_path, class: "btn-edit" %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.goal %>
    </div>
    <%= link_to "編集する", edit_tweet_path(t.id), class: "btn-edit" %>
    <%= button_to "削除する", tweet_path(t.id), method: :delete, class: "btn-delete" %>

  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="tweets-new">
 <h1>新規目標設定</h1>
 <%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :goal %>
    <%= f.text_field :goal, class: "goal-input" %>
  </div>
  <%= f.submit "目標にする", class: "btn-submit" %>
 <% end %>
 <%= link_to "目標一覧に戻る", tweets_path, class: "btn-back" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class=users>
  <h1>Working Person</h1>
  <div class="user-info-box">
   <p class="user-name">名前 : <%= @user.name %></p>
   <p class="user-email">メールアドレス : <%= @user.email %></p>
   <p class="user-profile">プロフィール : <%= @user.profile %></p>
  </div>

 <% if current_user.id == @user.id %>
<%= link_to "編集する", edit_user_registration_path, class: "btn-link" %>
 <% end %>

 <div class=list-title>Working Personの投稿一覧</div>
  <div class=post>
   <% @user.blogs.each do |t| %>
    <%= t.user.name %>
    <%= t.title %>
   <% end %>
  </div> 
 <div class=back><%= link_to "カレンダーに戻る", blogs_path, class: "btn-link" %></div>
</div>